### ISSUE TITLE
Configuration file generation

### ISSUE THREAD

**Issue by virtualtam** [shaarli/python-shaarli-client#17]
Mentioned in https://github.com/shaarli/python-shaarli-client/pull/15#pullrequestreview-28216704

Some ideas:
- add a `setup` subcommand
- automate configuration file generation (maybe first-time setup is enough?)

**Comment by nodiscc** [comment]
I think the documentation is enough: https://python-shaarli-client.readthedocs.io/en/latest/user/configuration.html. It shows an example of all available options (currently `url` and `secret`)

I'm in favor of closing this. Ping @ArthurHoaro since you originally requested the example config file

**Comment by ArthurHoaro** [comment]
Sure!
