### ISSUE TITLE
Use Pipenv for packaging/distribution/installation

### ISSUE THREAD

**Issue by nodiscc** [shaarli/python-shaarli-client#25]
https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies now recommends [Pipenv](https://docs.pipenv.org/) as the preferred packaging/installation method for Python projects. There is a short usage example at https://www.ostechnix.com/pipenv-officially-recommended-python-packaging-tool/.

It would be interesting to improve the virtualenv-based setup described at https://python-shaarli-client.readthedocs.io/en/latest/user/installation.html by using Pipenv which seems to abstarct away virtualenv management for end users, while retaining advantages of a venv setup.

**Comment by virtualtam** [comment]
Pipenv/Pipfile look promising, but the project doesn't seem to have gained as much traction as was hoped, and developers are still mostly using the traditional `setup.py` / `requirements.txt` / `pip` / `virtualenv` approach, with the assistance of well-established wrappers such as `virtualenvwrapper` and `pew`.

From my experience training beginner Python developers, I have a preference towards starting with `virtualenv` and `pip` to get a grasp of what's happening under the hood, before moving to more advanced tooling with `tox` and `pew`.

See:
- https://www.reddit.com/r/Python/comments/5pmb8o/announcing_pipenv_from_kenneth_reitz/
- https://www.kennethreitz.org/essays/pipenv-one-year-later-a-call-for-help
- https://www.reddit.com/r/Python/comments/7gr3qw/is_pipenv_still_the_official_reccomended_tool_for/
