### ISSUE TITLE
Documentation: provide a complete example

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/python-shaarli-client#50]
Currently the [Usage](https://python-shaarli-client.readthedocs.io/en/latest/user/usage.html) documentation page does not provide a complete example, with all field being used.

For example, I misused the `--tags` flag, as it is supposed to be an array of values instead of a string. See shaarli/Shaarli#1651

**Comment by nodiscc** [comment]
Usage of `--searchtags` is now properly documented https://python-shaarli-client.readthedocs.io/en/latest/user/usage.html#get-links
