### ISSUE TITLE
Define command line usage/workflow

### ISSUE THREAD

**Issue by nodiscc** [shaarli/python-shaarli-client#7]
This issue aims at defining command-line usage of the Shaarli API client.

 * Command line syntax (available parameters/arguments)
 * Output formatting (success/error messages/shaare listings/export to other formats)

Example CLI usage that comes to mind. Feel free to edit it with your suggested improvements:

```
    USAGE: shaarli-client.py SHAARLI_URL METHOD URI [--param1='value' --param2='value' ...]:
        available methods: GET, POST, PUT
        GET parameters: limit, searchterms, searchtags, offset, visibility, format
        POST parameters: url, tags, description
        PUT parameters: ...
    shaarli-client.py https://my.links.example/ GET /links/349
    shaarli-client.py https://my.links.example/ /links --limit=10 --searchterm=dankmemes
    shaarli-client.py https://my.links.example/ /links --visibility=private
    shaarli-client.py https://my.links.example/ POST /links --url="https://github.com/shaarli/python-shaarli-client" --tags="software,python" --description='A Python 3 Command-Line Interface to interact with a Shaarli instance.'
```

I'm unsure about how output format selection should be implemented/made available.
Should `--format` be an available parameter for GET, or can it be more loosely coupled? The client would output raw JSON, and extra actions could be ran:

    --actions=output_prettyprint,output_html,download_media,download_pages,send_archiveorg,...

It should also be possible to stash configuration values in a configuration file (eg. API token, default  shaarli_url,...)

**Comment by virtualtam** [comment]
Some ideas & resources :)

That's a lot of stuff covered, features can be introduced one at a time and refactored later (especially command & argument parsing) as the tool grows.

### Read configuration from a config file

> It should also be possible to stash configuration values in a configuration file (eg. API token, default shaarli_url,...)

Using [ConfigParser](https://docs.python.org/3/library/configparser.html):
- lets a user define credentials for several instances
- lets the instance be selectable from the CLI
- avoids passing authentication credentials on the CLI
- location precedence:
    - user-specified (optional CLI flag)
    - `.shaarli.ini`
    - `~/.config/shaarli.ini`

```ini
[my-shaarli-1]
url = https://my.shaarli.org/one/
secret = 1m4h53cr37

[my-shaarli-2]
url = https://my.other.shaarli.org/one/
secret = 1m4h53cr37
```

### Argparse for the win!

> Command line syntax (available parameters/arguments)

[Argparse](https://docs.python.org/3.6/library/argparse.html) is a very powerful CLI option parser that provides such niceties as:
- generated CLI help
- mandatory vs. optional parameters
- argument type and cardinality specification
- [subcommands](https://docs.python.org/3.6/library/argparse.html#sub-commands) to embed [parsers within the parser](https://cdn.meme.am/instances/500x/32584428.jpg)
- [mutually exclusive](https://docs.python.org/3.6/library/argparse.html#mutual-exclusion) option groups

Possible structure:
- global parser carrying global options
- one subparser per supported Shaarli REST endpoint
    - this allows only proposing supported HTTP methods
    - additional GET/POST/... parameters can be passed as [keyword arguments](https://pythontips.com/2013/08/04/args-and-kwargs-in-python-explained/) (kwargs)

Parser inheritance is also possible, should several commands come with similar arguments.

### Entrypoints & actions
Setuptools provides automatic console script creation through [entry_points](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation), so we can differentiate:
- CLI commands for plain API usage: send a query, get the response, print it
- CLI commands with added value: media download, web scraping...

### Output control

> Output formatting (success/error messages/shaare listings/export to other formats)

All HTTP methods:
- the server response header can be pretty-printed (status code + optional status message)

GET:
- the server response body can be:
    - pretty-printed, e.g. for `/info`
    - written to a file as JSON, e.g. when dumping all links
    - (opt. pretty-printed and) written to the standard outpu, e.g. for command piping
    - stored as an object for future usage, e.g. web crawling


### Interoperability

> export to other formats

Additional conversion is also possible but might be slightly out-of-scope / low-priority. JSON can be converted (loaded) as a Python dictionary and easily dumped to other popular formats, though I suspect users/developers might want to perform extra processing on the data structure.

**Comment by virtualtam** [comment]
Closing as we now have:
- parser generation from API endpoint metadata
- configuration file support
- output formatting
